# See https://prometheus.io/docs/alerting/configuration/ for documentation.

global:
receivers:
      - name: default-receiver
        webhook_configs:
          - url: "http://10.162.29.223:9999/hooks-default"
          - url: "http://10.162.32.38:9999/hooks-default"
          # this is for debugging
          - url: "http://10.163.16.126:9999/hooks-default"

      - name: ha-hook-receiver
        webhook_configs:
          - url: "http://10.162.29.223:9999/hooks-ha"
          # this is for debugging
          - url: "http://10.163.16.126:9999/hooks-default"

      - name: hana-hook-receiver
        webhook_configs:
          - url: "http://10.162.29.223:9999/hooks-sap"
          # this is for debugging
          - url: "http://10.163.16.126:9999/hooks-sap"


route:
  receiver: 'default-receiver'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  group_by: [alertname]
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.

  routes:
  # All alerts with component netweaver or hana are dispatched to sap-hook.
  - receiver: 'hana-hook-receiver'
    # overwrite default root value
    # group_wait: 10s
    match_re:
      component: hana
  # All alerts with the component label match this sub-route.
  - receiver: 'ha-hook-receiver'
    # group_by: [product, environment]
    match:
      component: sbd
